[36mATRI[0m | 03-17 18:15:44 | ERROR plugin.manager >> Failed to import "statistical"
Traceback (most recent call last):

  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fc8e54eff70>
           └ <ClickAliasedGroup main>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fc8e5767b20>
         │    └ <function MultiCommand.invoke at 0x7fc8e54f8040>
         └ <ClickAliasedGroup main>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fc8e575e2e0>
           │               │       │       └ <function Command.invoke at 0x7fc8e54f4a60>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fc8e575e2e0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fc8e5710dc0>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fc8e575e2e0>
           │   │      │    └ <function run at 0x7fc8e1c26160>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fc8e54ef820>
           └ <click.core.Context object at 0x7fc8e575e2e0>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()

  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fc8e1c0cb80>

  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7fc8e57d38b0>
             └ <module 'importlib' from '/usr/lib/python3.8/importlib/__init__.py'>

  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7fc8e5902430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/root/Projects/Kori-Bot/Kori-bot/./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7fc8e5215430>
    └ <module 'nonebot' from '/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7fc8e5206f70>
           └ <nonebot.plugin.manager.PluginManager object at 0x7fc8e1758e50>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(

  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7fc8e5206e50>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7fc8e1758e50>
                  │    │           │         └ 'statistical'
                  │    │           └ 'statistical'
                  │    └ <function PluginManager.load_plugin at 0x7fc8e5206ee0>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7fc8e1758e50>

> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7fc8e57d38b0>
             └ <module 'importlib' from '/usr/lib/python3.8/importlib/__init__.py'>

  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.statistical'
           │          └ <function _gcd_import at 0x7fc8e5902430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.statistical' from '/root/Projects/Kori-Bot/Kori-bot/./src/plugins/statistical/__init__.py'>

  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/root/Projects/Kori-Bot/Kori-bot/./src/plugins/statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "/root/Projects/Kori-Bot/Kori-bot/./src/plugins/statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "/root/Projects/Kori-Bot/Kori-bot/./src/plugins/statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       │    │    └ <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       │    └ <built-in function load>
                       └ <module 'ujson' from '/usr/local/lib/python3.8/dist-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-17 18:15:44 | WARNING nonebot >> Duplicated prefix rule "/lottery"
[36mATRI[0m | 03-17 18:15:44 | WARNING nonebot >> Duplicated prefix rule "!lottery"
[36mATRI[0m | 03-17 18:15:44 | WARNING nonebot >> Duplicated prefix rule "！lottery"
[36mATRI[0m | 03-17 18:39:23 | ERROR nonebot >> Running matcher <Matcher from src.plugins.repeater, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):

  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fc8e54eff70>
           └ <ClickAliasedGroup main>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fc8e5767b20>
         │    └ <function MultiCommand.invoke at 0x7fc8e54f8040>
         └ <ClickAliasedGroup main>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fc8e575e2e0>
           │               │       │       └ <function Command.invoke at 0x7fc8e54f4a60>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fc8e575e2e0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fc8e5710dc0>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fc8e575e2e0>
           │   │      │    └ <function run at 0x7fc8e1c26160>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fc8e54ef820>
           └ <click.core.Context object at 0x7fc8e575e2e0>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()

  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fc8e1c0cb80>

  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fc8e395e550>
    └ <module 'nonebot' from '/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fc8e395e0d0>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fc8e1b69940>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/dist-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fc8e1b69430>
    └ <uvicorn.server.Server object at 0x7fc8633be400>

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fc8e1b694c0>
           │       │   └ <uvicorn.server.Server object at 0x7fc8633be400>
           │       └ <function run at 0x7fc8e4834d30>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>

  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fc863401dc0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _event_to_me at 0x7fc8e397fdc0>: <Task finished name='Task-65607' coro=<_event_to_me() done, defined at /usr/local...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fc8b0eb0430>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}}
          │            │        │    └ GroupMessageEvent(time=1647513563, self_id=507346814, post_type='message', sub_type='normal', user_id=2548226969, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>
          │            └ <Matcher from src.plugins.repeater, type=message, priority=10, temp=False>
          └ <function _run_matcher at 0x7fc8e29acf70>

> File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _event_to_me at 0x7fc8e397fdc0>: <Task finished name='Task-65607' coro=<_event_to_me() done, defined at /usr/local...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fc8b0eb0430>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}}
          │       │   │    └ GroupMessageEvent(time=1647513563, self_id=507346814, post_type='message', sub_type='normal', user_id=2548226969, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>
          │       └ <function Matcher.run at 0x7fc8e397f940>
          └ <Matcher from src.plugins.repeater, type=message, priority=10, temp=False>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _event_to_me at 0x7fc8e397fdc0>: <Task finished name='Task-65607' coro=<_event_to_me() done, defined at /usr/local...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fc8b0eb0430>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}}
          │    │          │    └ GroupMessageEvent(time=1647513563, self_id=507346814, post_type='message', sub_type='normal', user_id=2548226969, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>
          │    └ <function Matcher.simple_run at 0x7fc8e397f8b0>
          └ <Matcher from src.plugins.repeater, type=message, priority=10, temp=False>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function repeater at 0x7fc8e147a700>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(na...

  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>, 'event': GroupMessageEvent(time=1647513563, self_id=5...
                 │    └ <function repeater at 0x7fc8e147a700>
                 └ <Dependent call=<function repeater at 0x7fc8e147a700>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(na...

  File "/root/Projects/Kori-Bot/Kori-bot/./src/plugins/repeater/__init__.py", line 35, in repeater
    mt = messageType(str(event.message))
         │               │     └ [MessageSegment(type='text', data={'text': ''})]
         │               └ GroupMessageEvent(time=1647513563, self_id=507346814, post_type='message', sub_type='normal', user_id=2548226969, message_typ...
         └ <function messageType at 0x7fc8e147a550>

  File "/root/Projects/Kori-Bot/Kori-bot/./src/plugins/repeater/__init__.py", line 17, in messageType
    if message[0] == "[":
       └ ''

IndexError: string index out of range
[36mATRI[0m | 03-17 18:56:13 | ERROR nonebot >> Running matcher <Matcher from src.plugins.russian, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):

  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fc8e54eff70>
           └ <ClickAliasedGroup main>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fc8e5767b20>
         │    └ <function MultiCommand.invoke at 0x7fc8e54f8040>
         └ <ClickAliasedGroup main>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fc8e575e2e0>
           │               │       │       └ <function Command.invoke at 0x7fc8e54f4a60>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fc8e575e2e0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fc8e5710dc0>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fc8e575e2e0>
           │   │      │    └ <function run at 0x7fc8e1c26160>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fc8e54ef820>
           └ <click.core.Context object at 0x7fc8e575e2e0>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()

  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fc8e1c0cb80>

  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fc8e395e550>
    └ <module 'nonebot' from '/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fc8e395e0d0>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fc8e1b69940>
    └ <module 'uvicorn' from '/usr/local/lib/python3.8/dist-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fc8e1b69430>
    └ <uvicorn.server.Server object at 0x7fc8633be400>

  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fc8e1b694c0>
           │       │   └ <uvicorn.server.Server object at 0x7fc8633be400>
           │       └ <function run at 0x7fc8e4834d30>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>

  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fc863401dc0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _event_to_me at 0x7fc8e397fdc0>: <Task finished name='Task-145968' coro=<_event_to_me() done, defined at /usr/loca...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fc848c14be0>
          │            │        │    │      └ {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': [MessageSegment(type='text', data={'text': 'sell ...
          │            │        │    └ GroupMessageEvent(time=1647514567, self_id=507346814, post_type='message', sub_type='normal', user_id=2082049330, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>
          │            └ <Matcher from src.plugins.russian, type=message, priority=5, temp=False>
          └ <function _run_matcher at 0x7fc8e29acf70>

> File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _event_to_me at 0x7fc8e397fdc0>: <Task finished name='Task-145968' coro=<_event_to_me() done, defined at /usr/loca...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fc848c14be0>
          │       │   │    │      └ {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': [MessageSegment(type='text', data={'text': 'sell ...
          │       │   │    └ GroupMessageEvent(time=1647514567, self_id=507346814, post_type='message', sub_type='normal', user_id=2082049330, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>
          │       └ <function Matcher.run at 0x7fc8e397f940>
          └ <Matcher from src.plugins.russian, type=message, priority=5, temp=False>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _event_to_me at 0x7fc8e397fdc0>: <Task finished name='Task-145968' coro=<_event_to_me() done, defined at /usr/loca...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fc848c14be0>
          │    │          │    │      └ {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': [MessageSegment(type='text', data={'text': 'sell ...
          │    │          │    └ GroupMessageEvent(time=1647514567, self_id=507346814, post_type='message', sub_type='normal', user_id=2082049330, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>
          │    └ <function Matcher.simple_run at 0x7fc8e397f8b0>
          └ <Matcher from src.plugins.russian, type=message, priority=5, temp=False>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7fc8ce752940>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>, 'event': GroupMessageEvent(time=1647514567, self_id=5...
                 │    └ <function _ at 0x7fc8ce752940>
                 └ <Dependent call=<function _ at 0x7fc8ce752940>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "/root/Projects/Kori-Bot/Kori-bot/./src/plugins/russian/__init__.py", line 518, in _
    await stock.finish(
          │     └ <classmethod object at 0x7fc8e3976c70>
          └ <Matcher from src.plugins.russian, type=message, priority=5, temp=False>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 464, in finish
    await cls.send(message, **kwargs)
          │   │    │          └ {'at_sender': True}
          │   │    └ '\n🧾 Successfully sold 2 shares earning 1557.86 coins.\nYou have 0 shares left now.\n🟩 Current stock: 778.93 coins,  27.64%'
          │   └ <classmethod object at 0x7fc8e3976c10>
          └ <Matcher from src.plugins.russian, type=message, priority=5, temp=False>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 449, in send
    return await bot.send(event=event, message=_message, **kwargs)
                 │   │          │              │           └ {'at_sender': True}
                 │   │          │              └ '\n🧾 Successfully sold 2 shares earning 1557.86 coins.\nYou have 0 shares left now.\n🟩 Current stock: 778.93 coins,  27.64%'
                 │   │          └ GroupMessageEvent(time=1647514567, self_id=507346814, post_type='message', sub_type='normal', user_id=2082049330, message_typ...
                 │   └ <function Bot.send at 0x7fc8e29dc4c0>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/onebot/v11/bot.py", line 247, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
                 │    │                      │     │      │          └ {'at_sender': True}
                 │    │                      │     │      └ '\n🧾 Successfully sold 2 shares earning 1557.86 coins.\nYou have 0 shares left now.\n🟩 Current stock: 778.93 coins,  27.64%'
                 │    │                      │     └ GroupMessageEvent(time=1647514567, self_id=507346814, post_type='message', sub_type='normal', user_id=2082049330, message_typ...
                 │    │                      └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>
                 │    └ <attribute '__class__' of 'object' objects>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/onebot/v11/bot.py", line 175, in send
    return await bot.send_msg(**params)
                 │              └ {'user_id': 2082049330, 'group_id': 937760225, 'message_type': 'group', 'message': [MessageSegment(type='at', data={'qq': '20...
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': 2082049330, 'group_id': 937760225, 'message_type': 'group', 'message': [MessageSegment(type='at', data={'qq': '20...
                                  └ 'send_msg'

  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 36}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': 2082049330, 'group_id': 937760225, 'message_type': 'group', 'message': [MessageSegment(type='at', data={'qq': '20...
                   │    │       │         │     └ 'send_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>
                   │    │       └ <function Adapter._call_api at 0x7fc8e29dc790>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fc8e1c2aaf0>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc863ead550>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fc8e29ffd30>

  File "/usr/local/lib/python3.8/dist-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 36}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhtt...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 36}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-17 20:00:01 | WARNING apscheduler >> Run time of job "change_price (trigger: cron[hour='8-21', minute='*', second='*/30'], next run at: 2022-03-17 20:00:30 CST)" was missed by 0:00:01.246836
[36mATRI[0m | 03-17 20:00:01 | WARNING apscheduler >> Run time of job "_ (trigger: cron[minute='*'], next run at: 2022-03-17 20:01:00 CST)" was missed by 0:00:01.247889
[36mATRI[0m | 03-17 20:32:19 | WARNING nonebot >> OneBot V11 | WebSocket for Bot 507346814 closed by peer
