[36mATRI[0m | 03-08 14:26:02 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fd93846b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fd92f4c1f40>
         │    └ <function MultiCommand.invoke at 0x7fd93846f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fd9406316a0>
           │               │       │       └ <function Command.invoke at 0x7fd93846baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fd9406316a0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fd92f3969d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fd9406316a0>
           │   │      │    └ <function run at 0x7fd92f4c08b0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fd9384678b0>
           └ <click.core.Context object at 0x7fd9406316a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fd92f4b0670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7fd94061f940>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7fd94074d430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7fd93632f790>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7fd936329310>
           └ <nonebot.plugin.manager.PluginManager object at 0x7fd92eca56d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7fd9363291f0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7fd92eca56d0>
                  │    │           │         └ 'nonebot_plugin_statistical'
                  │    │           └ 'nonebot_plugin_statistical'
                  │    └ <function PluginManager.load_plugin at 0x7fd936329280>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7fd92eca56d0>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7fd94061f940>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.nonebot_plugin_statistical'
           │          └ <function _gcd_import at 0x7fd94074d430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       │    │    └ <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       │    └ <built-in function load>
                       └ <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-08 14:26:11 | WARNING nonebot >> Duplicated prefix rule "!lottery"
[36mATRI[0m | 03-08 14:26:11 | WARNING nonebot >> Duplicated prefix rule "/lottery"
[36mATRI[0m | 03-08 14:26:11 | WARNING nonebot >> Duplicated prefix rule "！lottery"
[36mATRI[0m | 03-08 14:26:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 14:27:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fd93846b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fd92f4c1f40>
         │    └ <function MultiCommand.invoke at 0x7fd93846f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fd9406316a0>
           │               │       │       └ <function Command.invoke at 0x7fd93846baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fd9406316a0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fd92f3969d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fd9406316a0>
           │   │      │    └ <function run at 0x7fd92f4c08b0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fd9384678b0>
           └ <click.core.Context object at 0x7fd9406316a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fd92f4b0670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fd93159a940>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fd93159a4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fd92f2bc670>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fd92f2bca60>
    └ <uvicorn.server.Server object at 0x7fd8c36eda00>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fd92f2bcaf0>
           │       │   └ <uvicorn.server.Server object at 0x7fd8c36eda00>
           │       └ <function run at 0x7fd934cf3430>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fd8c37b4b40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=fe764b8330104f30a70440d94ba23991 name=change_price)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=fe764b8330104f30a70440d94ba23991 name=change_price)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=fe764b8330104f30a70440d94ba23991 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    │               └ <function RussianManager._price_change_handle at 0x7fd8c3788ee0>
    └ <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fd8c3779790>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 668, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         │    │                                         └ -3.42
                         │    └ <function RussianManager._check_stock_handle at 0x7fd8c3788e50>
                         └ <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fd8c3779790>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    money_per_stock = float(history_money_per_stock[-1])
                            └ ['532.799', '540.088', '550.311', '545.3789999999999', '556.384', '569.893', '568.394', '559.432', '551.1189999999999', '555....

ValueError: could not convert string to float: ''
[36mATRI[0m | 03-08 14:26:32 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fd93846b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fd92f4c1f40>
         │    └ <function MultiCommand.invoke at 0x7fd93846f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fd9406316a0>
           │               │       │       └ <function Command.invoke at 0x7fd93846baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fd9406316a0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fd92f3969d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fd9406316a0>
           │   │      │    └ <function run at 0x7fd92f4c08b0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fd9384678b0>
           └ <click.core.Context object at 0x7fd9406316a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fd92f4b0670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fd93159a940>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fd93159a4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fd92f2bc670>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fd92f2bca60>
    └ <uvicorn.server.Server object at 0x7fd8c36eda00>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fd92f2bcaf0>
           │       │   └ <uvicorn.server.Server object at 0x7fd8c36eda00>
           │       └ <function run at 0x7fd934cf3430>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fd8c37b4b40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fd93155b160>: <Task finished name='Task-880' coro=<_command() done, defined at /usr/local/python3/l...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fd8c2c85fa0>
          │            │        │    │      └ {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1646720791, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fd8c2c857c0>
          │            └ <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
          └ <function _run_matcher at 0x7fd92f3d8670>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fd93155b160>: <Task finished name='Task-880' coro=<_command() done, defined at /usr/local/python3/l...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fd8c2c85fa0>
          │       │   │    │      └ {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': []}}
          │       │   │    └ GroupMessageEvent(time=1646720791, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fd8c2c857c0>
          │       └ <function Matcher.run at 0x7fd9315d7b80>
          └ <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fd93155b160>: <Task finished name='Task-880' coro=<_command() done, defined at /usr/local/python3/l...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fd8c2c85fa0>
          │    │          │    │      └ {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': []}}
          │    │          │    └ GroupMessageEvent(time=1646720791, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fd8c2c857c0>
          │    └ <function Matcher.simple_run at 0x7fd9315d7af0>
          └ <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7fd8c36e5310>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fd8c2c857c0>, 'event': GroupMessageEvent(time=1646720791, self_id=5...
                 │    └ <function _ at 0x7fd8c36e5310>
                 └ <Dependent call=<function _ at 0x7fd8c36e5310>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 432, in _
    money_per_stock = russian_manager._check_stock_handle()["money_per_stock"]
                      │               └ <function RussianManager._check_stock_handle at 0x7fd8c3788e50>
                      └ <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fd8c3779790>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    money_per_stock = float(history_money_per_stock[-1])
                            └ ['532.799', '540.088', '550.311', '545.3789999999999', '556.384', '569.893', '568.394', '559.432', '551.1189999999999', '555....

ValueError: could not convert string to float: ''
[36mATRI[0m | 03-08 14:27:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 14:27:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fd93846b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fd92f4c1f40>
         │    └ <function MultiCommand.invoke at 0x7fd93846f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fd9406316a0>
           │               │       │       └ <function Command.invoke at 0x7fd93846baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fd9406316a0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fd92f3969d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fd9406316a0>
           │   │      │    └ <function run at 0x7fd92f4c08b0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fd9384678b0>
           └ <click.core.Context object at 0x7fd9406316a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fd92f4b0670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fd93159a940>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fd93159a4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fd92f2bc670>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fd92f2bca60>
    └ <uvicorn.server.Server object at 0x7fd8c36eda00>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fd92f2bcaf0>
           │       │   └ <uvicorn.server.Server object at 0x7fd8c36eda00>
           │       └ <function run at 0x7fd934cf3430>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fd8c37b4b40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=fe764b8330104f30a70440d94ba23991 name=change_price)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=fe764b8330104f30a70440d94ba23991 name=change_price)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=fe764b8330104f30a70440d94ba23991 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    │               └ <function RussianManager._price_change_handle at 0x7fd8c3788ee0>
    └ <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fd8c3779790>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 668, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         │    │                                         └ -5.804
                         │    └ <function RussianManager._check_stock_handle at 0x7fd8c3788e50>
                         └ <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fd8c3779790>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    money_per_stock = float(history_money_per_stock[-1])
                            └ ['532.799', '540.088', '550.311', '545.3789999999999', '556.384', '569.893', '568.394', '559.432', '551.1189999999999', '555....

ValueError: could not convert string to float: ''
[36mATRI[0m | 03-08 14:27:10 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fd93846b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fd92f4c1f40>
         │    └ <function MultiCommand.invoke at 0x7fd93846f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fd9406316a0>
           │               │       │       └ <function Command.invoke at 0x7fd93846baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fd9406316a0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fd92f3969d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fd9406316a0>
           │   │      │    └ <function run at 0x7fd92f4c08b0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fd9384678b0>
           └ <click.core.Context object at 0x7fd9406316a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fd92f4b0670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fd93159a940>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fd93159a4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fd92f2bc670>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fd92f2bca60>
    └ <uvicorn.server.Server object at 0x7fd8c36eda00>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fd92f2bcaf0>
           │       │   └ <uvicorn.server.Server object at 0x7fd8c36eda00>
           │       └ <function run at 0x7fd934cf3430>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fd8c37b4b40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fd93155b160>: <Task finished name='Task-2296' coro=<_command() done, defined at /usr/local/python3/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fd8c0bf67c0>
          │            │        │    │      └ {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': [MessageSegment(type='text', data={'text': 'me'})]}}
          │            │        │    └ GroupMessageEvent(time=1646720830, self_id=507346814, post_type='message', sub_type='normal', user_id=963046537, message_type...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fd8c2c857c0>
          │            └ <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
          └ <function _run_matcher at 0x7fd92f3d8670>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fd93155b160>: <Task finished name='Task-2296' coro=<_command() done, defined at /usr/local/python3/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fd8c0bf67c0>
          │       │   │    │      └ {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': [MessageSegment(type='text', data={'text': 'me'})]}}
          │       │   │    └ GroupMessageEvent(time=1646720830, self_id=507346814, post_type='message', sub_type='normal', user_id=963046537, message_type...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fd8c2c857c0>
          │       └ <function Matcher.run at 0x7fd9315d7b80>
          └ <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fd93155b160>: <Task finished name='Task-2296' coro=<_command() done, defined at /usr/local/python3/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fd8c0bf67c0>
          │    │          │    │      └ {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': [MessageSegment(type='text', data={'text': 'me'})]}}
          │    │          │    └ GroupMessageEvent(time=1646720830, self_id=507346814, post_type='message', sub_type='normal', user_id=963046537, message_type...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fd8c2c857c0>
          │    └ <function Matcher.simple_run at 0x7fd9315d7af0>
          └ <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7fd8c36e5310>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fd8c2c857c0>, 'event': GroupMessageEvent(time=1646720830, self_id=5...
                 │    └ <function _ at 0x7fd8c36e5310>
                 └ <Dependent call=<function _ at 0x7fd8c36e5310>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 432, in _
    money_per_stock = russian_manager._check_stock_handle()["money_per_stock"]
                      │               └ <function RussianManager._check_stock_handle at 0x7fd8c3788e50>
                      └ <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fd8c3779790>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    money_per_stock = float(history_money_per_stock[-1])
                            └ ['532.799', '540.088', '550.311', '545.3789999999999', '556.384', '569.893', '568.394', '559.432', '551.1189999999999', '555....

ValueError: could not convert string to float: ''
[36mATRI[0m | 03-08 14:27:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 14:28:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fd93846b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fd92f4c1f40>
         │    └ <function MultiCommand.invoke at 0x7fd93846f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fd9406316a0>
           │               │       │       └ <function Command.invoke at 0x7fd93846baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fd9406316a0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fd92f3969d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fd9406316a0>
           │   │      │    └ <function run at 0x7fd92f4c08b0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fd9384678b0>
           └ <click.core.Context object at 0x7fd9406316a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fd92f4b0670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fd93159a940>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fd93159a4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fd92f2bc670>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fd92f2bca60>
    └ <uvicorn.server.Server object at 0x7fd8c36eda00>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fd92f2bcaf0>
           │       │   └ <uvicorn.server.Server object at 0x7fd8c36eda00>
           │       └ <function run at 0x7fd934cf3430>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fd8c37b4b40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=fe764b8330104f30a70440d94ba23991 name=change_price)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=fe764b8330104f30a70440d94ba23991 name=change_price)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=fe764b8330104f30a70440d94ba23991 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    │               └ <function RussianManager._price_change_handle at 0x7fd8c3788ee0>
    └ <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fd8c3779790>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 668, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         │    │                                         └ -3.143
                         │    └ <function RussianManager._check_stock_handle at 0x7fd8c3788e50>
                         └ <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fd8c3779790>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    money_per_stock = float(history_money_per_stock[-1])
                            └ ['532.799', '540.088', '550.311', '545.3789999999999', '556.384', '569.893', '568.394', '559.432', '551.1189999999999', '555....

ValueError: could not convert string to float: ''
[36mATRI[0m | 03-08 14:27:30 | WARNING nonebot >> OneBot V11 | WebSocket for Bot 507346814 closed by peer
[36mATRI[0m | 03-08 14:33:36 | ERROR plugin.manager >> Failed to import "nonebot_plugin_russian"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f6c25db3040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f6c266394f0>
         │    └ <function MultiCommand.invoke at 0x7f6c25db70d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f6c2df26370>
           │               │       │       └ <function Command.invoke at 0x7f6c25db3af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f6c2df26370>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f6c1ccdf9d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f6c2df26370>
           │   │      │    └ <function run at 0x7f6c1ce098b0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f6c25daf8b0>
           └ <click.core.Context object at 0x7f6c2df26370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f6c1cdf8670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7f6c2df67940>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7f6c2e095430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7f6c23c77790>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f6c23c71310>
           └ <nonebot.plugin.manager.PluginManager object at 0x7f6c1c5eba90>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7f6c23c711f0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7f6c1c5eba90>
                  │    │           │         └ 'nonebot_plugin_russian'
                  │    │           └ 'nonebot_plugin_russian'
                  │    └ <function PluginManager.load_plugin at 0x7f6c23c71280>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7f6c1c5eba90>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f6c2df67940>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.nonebot_plugin_russian'
           │          └ <function _gcd_import at 0x7f6c2e095430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.nonebot_plugin_russian' from './src/plugins/nonebot_plugin_russian/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 15, in <module>
    from .data_source import russian_manager, max_bet_gold

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652
    history_money_per_stock.remove('')
                                     ^

TabError: inconsistent use of tabs and spaces in indentation
[36mATRI[0m | 03-08 14:33:50 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f6c25db3040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f6c266394f0>
         │    └ <function MultiCommand.invoke at 0x7f6c25db70d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f6c2df26370>
           │               │       │       └ <function Command.invoke at 0x7f6c25db3af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f6c2df26370>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f6c1ccdf9d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f6c2df26370>
           │   │      │    └ <function run at 0x7f6c1ce098b0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f6c25daf8b0>
           └ <click.core.Context object at 0x7f6c2df26370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f6c1cdf8670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7f6c2df67940>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7f6c2e095430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7f6c23c77790>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f6c23c71310>
           └ <nonebot.plugin.manager.PluginManager object at 0x7f6c1c5eba90>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7f6c23c711f0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7f6c1c5eba90>
                  │    │           │         └ 'nonebot_plugin_statistical'
                  │    │           └ 'nonebot_plugin_statistical'
                  │    └ <function PluginManager.load_plugin at 0x7f6c23c71280>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7f6c1c5eba90>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f6c2df67940>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.nonebot_plugin_statistical'
           │          └ <function _gcd_import at 0x7f6c2e095430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       │    │    └ <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       │    └ <built-in function load>
                       └ <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-08 15:09:20 | WARNING nonebot >> OneBot V11 | WebSocket for Bot 507346814 closed by peer
