[36mATRI[0m | 03-08 15:09:36 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f366f721040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f3666775fd0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f366f7250d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f366f721af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f36778e76a0>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f366664c9d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f36667778b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f366f71d8b0>
           â”” <click.core.Context object at 0x7f36778e76a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f3666766670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             â”‚         â”‚             â”” 'bot'
             â”‚         â”” <function import_module at 0x7f36778d4940>
             â”” <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           â”‚          â”‚           â”‚    â”‚        â”‚        â”” 0
           â”‚          â”‚           â”‚    â”‚        â”” None
           â”‚          â”‚           â”‚    â”” 0
           â”‚          â”‚           â”” 'bot'
           â”‚          â”” <function _gcd_import at 0x7f3677a03430>
           â”” <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    â”‚       â”” <function load_plugins at 0x7f366d5e5790>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           â”‚       â”” <function PluginManager.load_all_plugins at 0x7f366d5df310>
           â”” <nonebot.plugin.manager.PluginManager object at 0x7f3665f5b760>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  â”‚    â”‚           â”‚         â”‚       â”‚    â”” <function PluginManager.list_plugins at 0x7f366d5df1f0>
                  â”‚    â”‚           â”‚         â”‚       â”” <nonebot.plugin.manager.PluginManager object at 0x7f3665f5b760>
                  â”‚    â”‚           â”‚         â”” 'nonebot_plugin_statistical'
                  â”‚    â”‚           â”” 'nonebot_plugin_statistical'
                  â”‚    â”” <function PluginManager.load_plugin at 0x7f366d5df280>
                  â”” <nonebot.plugin.manager.PluginManager object at 0x7f3665f5b760>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             â”‚         â”” <function import_module at 0x7f36778d4940>
             â”” <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           â”‚          â”‚           â”‚    â”‚        â”‚        â”” 0
           â”‚          â”‚           â”‚    â”‚        â”” None
           â”‚          â”‚           â”‚    â”” 0
           â”‚          â”‚           â”” 'src.plugins.nonebot_plugin_statistical'
           â”‚          â”” <function _gcd_import at 0x7f3677a03430>
           â”” <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        â”” <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       â”‚    â”‚    â”” <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       â”‚    â”” <built-in function load>
                       â”” <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-08 15:10:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:10:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f366f721040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f3666775fd0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f366f7250d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f366f721af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f36778e76a0>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f366664c9d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f36667778b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f366f71d8b0>
           â”” <click.core.Context object at 0x7f36778e76a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f3666766670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f3668850940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f36688504c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f3666573670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f3666573a60>
    â”” <uvicorn.server.Server object at 0x7f35faef1970>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f3666573af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f35faef1970>
           â”‚       â”” <function run at 0x7f366bfa9430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f35faecce40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f364c2e43a0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f364ef80d30>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 669, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” 2.05
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f364c2e4310>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f364ef80d30>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    if '' in history_money_per_stock:

NameError: name 'history_money_per_stock' is not defined
[36mATRI[0m | 03-08 15:10:01 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f366f721040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f3666775fd0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f366f7250d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f366f721af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f36778e76a0>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f366664c9d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f36667778b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f366f71d8b0>
           â”” <click.core.Context object at 0x7f36778e76a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f3666766670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f3668850940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f36688504c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f3666573670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f3666573a60>
    â”” <uvicorn.server.Server object at 0x7f35faef1970>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f3666573af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f35faef1970>
           â”‚       â”” <function run at 0x7f366bfa9430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f35faecce40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          â”‚            â”‚        â”‚    â”‚      â”‚      â”‚      â”” {<function _command at 0x7f3668811160>: <Task finished name='Task-881' coro=<_command() done, defined at /usr/local/python3/l...
          â”‚            â”‚        â”‚    â”‚      â”‚      â”” <contextlib.AsyncExitStack object at 0x7f35fa416be0>
          â”‚            â”‚        â”‚    â”‚      â”” {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': []}}
          â”‚            â”‚        â”‚    â”” GroupMessageEvent(time=1646723400, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          â”‚            â”‚        â”” <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f35fa4165e0>
          â”‚            â”” <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
          â”” <function _run_matcher at 0x7f366668e670>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          â”‚       â”‚   â”‚    â”‚      â”‚      â”‚      â”” {<function _command at 0x7f3668811160>: <Task finished name='Task-881' coro=<_command() done, defined at /usr/local/python3/l...
          â”‚       â”‚   â”‚    â”‚      â”‚      â”” <contextlib.AsyncExitStack object at 0x7f35fa416be0>
          â”‚       â”‚   â”‚    â”‚      â”” {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': []}}
          â”‚       â”‚   â”‚    â”” GroupMessageEvent(time=1646723400, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          â”‚       â”‚   â”” <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f35fa4165e0>
          â”‚       â”” <function Matcher.run at 0x7f366888db80>
          â”” <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          â”‚    â”‚          â”‚    â”‚      â”‚      â”‚      â”” {<function _command at 0x7f3668811160>: <Task finished name='Task-881' coro=<_command() done, defined at /usr/local/python3/l...
          â”‚    â”‚          â”‚    â”‚      â”‚      â”” <contextlib.AsyncExitStack object at 0x7f35fa416be0>
          â”‚    â”‚          â”‚    â”‚      â”” {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': []}}
          â”‚    â”‚          â”‚    â”” GroupMessageEvent(time=1646723400, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          â”‚    â”‚          â”” <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f35fa4165e0>
          â”‚    â”” <function Matcher.simple_run at 0x7f366888daf0>
          â”” <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          â”” <Dependent call=<function _ at 0x7f364c16ca60>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 â”‚    â”‚      â”” {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f35fa4165e0>, 'event': GroupMessageEvent(time=1646723400, self_id=5...
                 â”‚    â”” <function _ at 0x7f364c16ca60>
                 â”” <Dependent call=<function _ at 0x7f364c16ca60>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 432, in _
    money_per_stock = russian_manager._check_stock_handle()["money_per_stock"]
                      â”‚               â”” <function RussianManager._check_stock_handle at 0x7f364c2e4310>
                      â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f364ef80d30>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    if '' in history_money_per_stock:

NameError: name 'history_money_per_stock' is not defined
[36mATRI[0m | 03-08 15:10:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:11:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f366f721040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f3666775fd0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f366f7250d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f366f721af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f36778e76a0>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f366664c9d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f36667778b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f366f71d8b0>
           â”” <click.core.Context object at 0x7f36778e76a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f3666766670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f3668850940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f36688504c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f3666573670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f3666573a60>
    â”” <uvicorn.server.Server object at 0x7f35faef1970>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f3666573af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f35faef1970>
           â”‚       â”” <function run at 0x7f366bfa9430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f35faecce40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f364c2e43a0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f364ef80d30>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 669, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” -11.667
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f364c2e4310>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f364ef80d30>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    if '' in history_money_per_stock:

NameError: name 'history_money_per_stock' is not defined
[36mATRI[0m | 03-08 15:11:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:11:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f366f721040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f3666775fd0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f366f7250d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f366f721af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f36778e76a0>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f366664c9d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f36667778b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f366f71d8b0>
           â”” <click.core.Context object at 0x7f36778e76a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f3666766670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f3668850940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f36688504c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f3666573670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f3666573a60>
    â”” <uvicorn.server.Server object at 0x7f35faef1970>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f3666573af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f35faef1970>
           â”‚       â”” <function run at 0x7f366bfa9430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f35faecce40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f364c2e43a0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f364ef80d30>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 669, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” -1.305
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f364c2e4310>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f364ef80d30>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    if '' in history_money_per_stock:

NameError: name 'history_money_per_stock' is not defined
[36mATRI[0m | 03-08 15:11:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:12:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f366f721040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f3666775fd0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f366f7250d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f366f721af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f36778e76a0>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f366664c9d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f36778e76a0>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f36667778b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f366f71d8b0>
           â”” <click.core.Context object at 0x7f36778e76a0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f3666766670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f3668850940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f36688504c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f3666573670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f3666573a60>
    â”” <uvicorn.server.Server object at 0x7f35faef1970>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f3666573af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f35faef1970>
           â”‚       â”” <function run at 0x7f366bfa9430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f35faecce40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=d9fbb5ae8c6c4abf9d402b62c931fc17 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f364c2e43a0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f364ef80d30>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 669, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” -15.304
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f364c2e4310>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f364ef80d30>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 652, in _check_stock_handle
    if '' in history_money_per_stock:

NameError: name 'history_money_per_stock' is not defined
[36mATRI[0m | 03-08 15:12:00 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f768042d040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f7680cb34f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f76804310d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f76885a0370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f768042daf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f76885a0370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f76773589d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f76885a0370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f76774838b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f76804298b0>
           â”” <click.core.Context object at 0x7f76885a0370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f7677472670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             â”‚         â”‚             â”” 'bot'
             â”‚         â”” <function import_module at 0x7f76885e1940>
             â”” <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           â”‚          â”‚           â”‚    â”‚        â”‚        â”” 0
           â”‚          â”‚           â”‚    â”‚        â”” None
           â”‚          â”‚           â”‚    â”” 0
           â”‚          â”‚           â”” 'bot'
           â”‚          â”” <function _gcd_import at 0x7f768870f430>
           â”” <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    â”‚       â”” <function load_plugins at 0x7f767e2f1790>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           â”‚       â”” <function PluginManager.load_all_plugins at 0x7f767e2eb310>
           â”” <nonebot.plugin.manager.PluginManager object at 0x7f7676c669d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  â”‚    â”‚           â”‚         â”‚       â”‚    â”” <function PluginManager.list_plugins at 0x7f767e2eb1f0>
                  â”‚    â”‚           â”‚         â”‚       â”” <nonebot.plugin.manager.PluginManager object at 0x7f7676c669d0>
                  â”‚    â”‚           â”‚         â”” 'nonebot_plugin_statistical'
                  â”‚    â”‚           â”” 'nonebot_plugin_statistical'
                  â”‚    â”” <function PluginManager.load_plugin at 0x7f767e2eb280>
                  â”” <nonebot.plugin.manager.PluginManager object at 0x7f7676c669d0>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             â”‚         â”” <function import_module at 0x7f76885e1940>
             â”” <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           â”‚          â”‚           â”‚    â”‚        â”‚        â”” 0
           â”‚          â”‚           â”‚    â”‚        â”” None
           â”‚          â”‚           â”‚    â”” 0
           â”‚          â”‚           â”” 'src.plugins.nonebot_plugin_statistical'
           â”‚          â”” <function _gcd_import at 0x7f768870f430>
           â”” <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        â”” <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       â”‚    â”‚    â”” <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       â”‚    â”” <built-in function load>
                       â”” <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-08 15:12:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:13:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f768042d040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f7680cb34f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f76804310d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f76885a0370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f768042daf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f76885a0370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f76773589d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f76885a0370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f76774838b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f76804298b0>
           â”” <click.core.Context object at 0x7f76885a0370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f7677472670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f7679d10940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f7679d104c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f767727e670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f767727ea60>
    â”” <uvicorn.server.Server object at 0x7f760b6c4700>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f767727eaf0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f760b6c4700>
           â”‚       â”” <function run at 0x7f767ccb5430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f760b6cfe40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f760f99ee50>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f760fa426a0>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 669, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” -14.705
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f760f99edc0>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f760fa426a0>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 654, in _check_stock_handle
    money_per_stock = round(money_per_stock * 100)

UnboundLocalError: local variable 'money_per_stock' referenced before assignment
[36mATRI[0m | 03-08 15:12:30 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f768042d040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f7680cb34f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f76804310d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f76885a0370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f768042daf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f76885a0370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f76773589d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f76885a0370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f76774838b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f76804298b0>
           â”” <click.core.Context object at 0x7f76885a0370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f7677472670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f7679d10940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f7679d104c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f767727e670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f767727ea60>
    â”” <uvicorn.server.Server object at 0x7f760b6c4700>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f767727eaf0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f760b6c4700>
           â”‚       â”” <function run at 0x7f767ccb5430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f760b6cfe40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          â”‚            â”‚        â”‚    â”‚      â”‚      â”‚      â”” {<function _command at 0x7f767951d160>: <Task finished name='Task-879' coro=<_command() done, defined at /usr/local/python3/l...
          â”‚            â”‚        â”‚    â”‚      â”‚      â”” <contextlib.AsyncExitStack object at 0x7f760ac519a0>
          â”‚            â”‚        â”‚    â”‚      â”” {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': []}}
          â”‚            â”‚        â”‚    â”” GroupMessageEvent(time=1646723549, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          â”‚            â”‚        â”” <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f760ac51760>
          â”‚            â”” <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
          â”” <function _run_matcher at 0x7f767739a670>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          â”‚       â”‚   â”‚    â”‚      â”‚      â”‚      â”” {<function _command at 0x7f767951d160>: <Task finished name='Task-879' coro=<_command() done, defined at /usr/local/python3/l...
          â”‚       â”‚   â”‚    â”‚      â”‚      â”” <contextlib.AsyncExitStack object at 0x7f760ac519a0>
          â”‚       â”‚   â”‚    â”‚      â”” {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': []}}
          â”‚       â”‚   â”‚    â”” GroupMessageEvent(time=1646723549, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          â”‚       â”‚   â”” <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f760ac51760>
          â”‚       â”” <function Matcher.run at 0x7f7679599b80>
          â”” <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          â”‚    â”‚          â”‚    â”‚      â”‚      â”‚      â”” {<function _command at 0x7f767951d160>: <Task finished name='Task-879' coro=<_command() done, defined at /usr/local/python3/l...
          â”‚    â”‚          â”‚    â”‚      â”‚      â”” <contextlib.AsyncExitStack object at 0x7f760ac519a0>
          â”‚    â”‚          â”‚    â”‚      â”” {'_prefix': {'command': ('stock',), 'raw_command': '/stock', 'command_arg': []}}
          â”‚    â”‚          â”‚    â”” GroupMessageEvent(time=1646723549, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          â”‚    â”‚          â”” <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f760ac51760>
          â”‚    â”” <function Matcher.simple_run at 0x7f7679599af0>
          â”” <Matcher from src.plugins.nonebot_plugin_russian, type=message, priority=5, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          â”” <Dependent call=<function _ at 0x7f760f9cdc10>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 â”‚    â”‚      â”” {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f760ac51760>, 'event': GroupMessageEvent(time=1646723549, self_id=5...
                 â”‚    â”” <function _ at 0x7f760f9cdc10>
                 â”” <Dependent call=<function _ at 0x7f760f9cdc10>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 432, in _
    money_per_stock = russian_manager._check_stock_handle()["money_per_stock"]
                      â”‚               â”” <function RussianManager._check_stock_handle at 0x7f760f99edc0>
                      â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f760fa426a0>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 654, in _check_stock_handle
    money_per_stock = round(money_per_stock * 100)

UnboundLocalError: local variable 'money_per_stock' referenced before assignment
[36mATRI[0m | 03-08 15:13:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:13:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f768042d040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f7680cb34f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f76804310d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f76885a0370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f768042daf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f76885a0370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f76773589d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f76885a0370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f76774838b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f76804298b0>
           â”” <click.core.Context object at 0x7f76885a0370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f7677472670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f7679d10940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f7679d104c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f767727e670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f767727ea60>
    â”” <uvicorn.server.Server object at 0x7f760b6c4700>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f767727eaf0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f760b6c4700>
           â”‚       â”” <function run at 0x7f767ccb5430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f760b6cfe40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f760f99ee50>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f760fa426a0>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 669, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” 3.669
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f760f99edc0>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f760fa426a0>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 654, in _check_stock_handle
    money_per_stock = round(money_per_stock * 100)

UnboundLocalError: local variable 'money_per_stock' referenced before assignment
[36mATRI[0m | 03-08 15:13:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:14:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f768042d040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f7680cb34f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f76804310d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f76885a0370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f768042daf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f76885a0370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f76773589d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f76885a0370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f76774838b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f76804298b0>
           â”” <click.core.Context object at 0x7f76885a0370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f7677472670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f7679d10940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f7679d104c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f767727e670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f767727ea60>
    â”” <uvicorn.server.Server object at 0x7f760b6c4700>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f767727eaf0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f760b6c4700>
           â”‚       â”” <function run at 0x7f767ccb5430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f760b6cfe40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f760f99ee50>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f760fa426a0>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 669, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” 10.536
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f760f99edc0>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f760fa426a0>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 654, in _check_stock_handle
    money_per_stock = round(money_per_stock * 100)

UnboundLocalError: local variable 'money_per_stock' referenced before assignment
[36mATRI[0m | 03-08 15:14:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:14:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f768042d040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f7680cb34f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f76804310d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f76885a0370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f768042daf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f76885a0370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f76773589d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f76885a0370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f76774838b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f76804298b0>
           â”” <click.core.Context object at 0x7f76885a0370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f7677472670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f7679d10940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f7679d104c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f767727e670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f767727ea60>
    â”” <uvicorn.server.Server object at 0x7f760b6c4700>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f767727eaf0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f760b6c4700>
           â”‚       â”” <function run at 0x7f767ccb5430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f760b6cfe40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=2396f6b91a4b4a31a3bd5bcd8be720d9 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f760f99ee50>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f760fa426a0>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 669, in _price_change_handle
    with open(price_path, 'a+') as f:
              â”‚                    â”” <_io.TextIOWrapper name='data/russian/stock_price.txt' mode='a+' encoding='UTF-8'>
              â”” PosixPath('data/russian/stock_price.txt')

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 654, in _check_stock_handle
    money_per_stock = history_money_per_stock[-1]
                      â”” ['532.799', '540.088', '550.311', '545.3789999999999', '556.384', '569.893', '568.394', '559.432', '551.1189999999999', '555....

UnboundLocalError: local variable 'money_per_stock' referenced before assignment
[36mATRI[0m | 03-08 15:14:26 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7fe6395bb040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7fe639e414f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7fe6395bf0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7fe64172e370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7fe6395bbaf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7fe64172e370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7fe6304e79d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7fe64172e370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7fe6306118b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7fe6395b78b0>
           â”” <click.core.Context object at 0x7fe64172e370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7fe630600670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             â”‚         â”‚             â”” 'bot'
             â”‚         â”” <function import_module at 0x7fe64176f940>
             â”” <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           â”‚          â”‚           â”‚    â”‚        â”‚        â”” 0
           â”‚          â”‚           â”‚    â”‚        â”” None
           â”‚          â”‚           â”‚    â”” 0
           â”‚          â”‚           â”” 'bot'
           â”‚          â”” <function _gcd_import at 0x7fe64189d430>
           â”” <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    â”‚       â”” <function load_plugins at 0x7fe63747f790>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           â”‚       â”” <function PluginManager.load_all_plugins at 0x7fe637479310>
           â”” <nonebot.plugin.manager.PluginManager object at 0x7fe62fdf4a60>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  â”‚    â”‚           â”‚         â”‚       â”‚    â”” <function PluginManager.list_plugins at 0x7fe6374791f0>
                  â”‚    â”‚           â”‚         â”‚       â”” <nonebot.plugin.manager.PluginManager object at 0x7fe62fdf4a60>
                  â”‚    â”‚           â”‚         â”” 'nonebot_plugin_statistical'
                  â”‚    â”‚           â”” 'nonebot_plugin_statistical'
                  â”‚    â”” <function PluginManager.load_plugin at 0x7fe637479280>
                  â”” <nonebot.plugin.manager.PluginManager object at 0x7fe62fdf4a60>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             â”‚         â”” <function import_module at 0x7fe64176f940>
             â”” <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           â”‚          â”‚           â”‚    â”‚        â”‚        â”” 0
           â”‚          â”‚           â”‚    â”‚        â”” None
           â”‚          â”‚           â”‚    â”” 0
           â”‚          â”‚           â”” 'src.plugins.nonebot_plugin_statistical'
           â”‚          â”” <function _gcd_import at 0x7fe64189d430>
           â”” <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        â”” <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       â”‚    â”‚    â”” <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       â”‚    â”” <built-in function load>
                       â”” <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-08 15:14:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:15:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7fe6395bb040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7fe639e414f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7fe6395bf0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7fe64172e370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7fe6395bbaf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7fe64172e370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7fe6304e79d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7fe64172e370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7fe6306118b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7fe6395b78b0>
           â”” <click.core.Context object at 0x7fe64172e370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7fe630600670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7fe632e9e940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7fe632e9e4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7fe63040d670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7fe63040da60>
    â”” <uvicorn.server.Server object at 0x7fe5c4d7a910>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7fe63040daf0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7fe5c4d7a910>
           â”‚       â”” <function run at 0x7fe635e43430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7fe5c4d62f40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7fe5c50284c0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fe5c502da90>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 670, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” -7.163
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7fe5c5028430>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fe5c502da90>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 655, in _check_stock_handle
    money_per_stock = round(money_per_stock * 100)
                            â”” '307.659'

TypeError: type str doesn't define __round__ method
[36mATRI[0m | 03-08 15:15:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:15:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7fe6395bb040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7fe639e414f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7fe6395bf0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7fe64172e370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7fe6395bbaf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7fe64172e370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7fe6304e79d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7fe64172e370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7fe6306118b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7fe6395b78b0>
           â”” <click.core.Context object at 0x7fe64172e370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7fe630600670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7fe632e9e940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7fe632e9e4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7fe63040d670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7fe63040da60>
    â”” <uvicorn.server.Server object at 0x7fe5c4d7a910>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7fe63040daf0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7fe5c4d7a910>
           â”‚       â”” <function run at 0x7fe635e43430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7fe5c4d62f40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7fe5c50284c0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fe5c502da90>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 670, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” 0.41
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7fe5c5028430>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fe5c502da90>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 655, in _check_stock_handle
    money_per_stock = round(money_per_stock * 100)
                            â”” '307.659'

TypeError: type str doesn't define __round__ method
[36mATRI[0m | 03-08 15:15:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:16:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7fe6395bb040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7fe639e414f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7fe6395bf0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7fe64172e370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7fe6395bbaf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7fe64172e370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7fe6304e79d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7fe64172e370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7fe6306118b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7fe6395b78b0>
           â”” <click.core.Context object at 0x7fe64172e370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7fe630600670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7fe632e9e940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7fe632e9e4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7fe63040d670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7fe63040da60>
    â”” <uvicorn.server.Server object at 0x7fe5c4d7a910>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7fe63040daf0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7fe5c4d7a910>
           â”‚       â”” <function run at 0x7fe635e43430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7fe5c4d62f40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7fe5c50284c0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fe5c502da90>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 670, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” -1.506
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7fe5c5028430>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fe5c502da90>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 655, in _check_stock_handle
    money_per_stock = round(money_per_stock * 100)
                            â”” '307.659'

TypeError: type str doesn't define __round__ method
[36mATRI[0m | 03-08 15:16:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:16:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7fe6395bb040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7fe639e414f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7fe6395bf0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7fe64172e370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7fe6395bbaf0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7fe64172e370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7fe6304e79d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7fe64172e370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7fe6306118b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7fe6395b78b0>
           â”” <click.core.Context object at 0x7fe64172e370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7fe630600670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7fe632e9e940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7fe632e9e4c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7fe63040d670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7fe63040da60>
    â”” <uvicorn.server.Server object at 0x7fe5c4d7a910>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7fe63040daf0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7fe5c4d7a910>
           â”‚       â”” <function run at 0x7fe635e43430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7fe5c4d62f40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=b4637afc5aa846088d451a71e88ce030 name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7fe5c50284c0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7fe5c502da90>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 670, in _price_change_handle
    with open(price_path, 'a+') as f:
              â”‚                    â”” <_io.TextIOWrapper name='data/russian/stock_price.txt' mode='a+' encoding='UTF-8'>
              â”” PosixPath('data/russian/stock_price.txt')

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 655, in _check_stock_handle
    money_per_stock =int(money_per_stock)
                         â”” '307.659'

TypeError: type str doesn't define __round__ method
[36mATRI[0m | 03-08 15:17:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:17:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f1ffca66040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f1ffd2ec4f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f1ffca6a0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f1ffca66af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f2004bd9370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f1ff39929d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f1ff3abc8b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f1ffca628b0>
           â”” <click.core.Context object at 0x7f2004bd9370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f1ff3aab670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f1ff5b95940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f1ff5b954c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f1ff38b8670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f1ff38b8a60>
    â”” <uvicorn.server.Server object at 0x7f1f87d52280>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f1ff38b8af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f1f87d52280>
           â”‚       â”” <function run at 0x7f1ff92ee430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f1f87caaf40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f1fe88494c0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 671, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” 11.492
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f1fe8849430>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 655, in _check_stock_handle
    money_per_stock =int(money_per_stock)
                         â”” '307.659'

ValueError: invalid literal for int() with base 10: '307.659'
[36mATRI[0m | 03-08 15:17:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:18:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f1ffca66040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f1ffd2ec4f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f1ffca6a0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f1ffca66af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f2004bd9370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f1ff39929d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f1ff3abc8b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f1ffca628b0>
           â”” <click.core.Context object at 0x7f2004bd9370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f1ff3aab670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f1ff5b95940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f1ff5b954c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f1ff38b8670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f1ff38b8a60>
    â”” <uvicorn.server.Server object at 0x7f1f87d52280>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f1ff38b8af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f1f87d52280>
           â”‚       â”” <function run at 0x7f1ff92ee430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f1f87caaf40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f1fe88494c0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 671, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” 0.532
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f1fe8849430>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 655, in _check_stock_handle
    money_per_stock =int(money_per_stock)
                         â”” '307.659'

ValueError: invalid literal for int() with base 10: '307.659'
[36mATRI[0m | 03-08 15:18:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:18:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f1ffca66040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f1ffd2ec4f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f1ffca6a0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f1ffca66af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f2004bd9370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f1ff39929d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f1ff3abc8b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f1ffca628b0>
           â”” <click.core.Context object at 0x7f2004bd9370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f1ff3aab670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f1ff5b95940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f1ff5b954c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f1ff38b8670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f1ff38b8a60>
    â”” <uvicorn.server.Server object at 0x7f1f87d52280>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f1ff38b8af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f1f87d52280>
           â”‚       â”” <function run at 0x7f1ff92ee430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f1f87caaf40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f1fe88494c0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 671, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” -13.336
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f1fe8849430>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 655, in _check_stock_handle
    money_per_stock =int(money_per_stock)
                         â”” '307.659'

ValueError: invalid literal for int() with base 10: '307.659'
[36mATRI[0m | 03-08 15:18:30 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:19:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f1ffca66040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f1ffd2ec4f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f1ffca6a0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f1ffca66af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f2004bd9370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f1ff39929d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f1ff3abc8b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f1ffca628b0>
           â”” <click.core.Context object at 0x7f2004bd9370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f1ff3aab670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f1ff5b95940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f1ff5b954c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f1ff38b8670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f1ff38b8a60>
    â”” <uvicorn.server.Server object at 0x7f1f87d52280>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f1ff38b8af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f1f87d52280>
           â”‚       â”” <function run at 0x7f1ff92ee430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f1f87caaf40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f1fe88494c0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 671, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” 8.753
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f1fe8849430>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 655, in _check_stock_handle
    money_per_stock =int(money_per_stock)
                         â”” '307.659'

ValueError: invalid literal for int() with base 10: '307.659'
[36mATRI[0m | 03-08 15:19:00 | ERROR apscheduler >> Job "change_price (trigger: cron[hour='8-22', minute='*', second='*/30'], next run at: 2022-03-08 15:19:30 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7f1ffca66040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7f1ffd2ec4f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7f1ffca6a0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7f1ffca66af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7f2004bd9370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7f1ff39929d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7f2004bd9370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7f1ff3abc8b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7f1ffca628b0>
           â”” <click.core.Context object at 0x7f2004bd9370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7f1ff3aab670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    â”‚       â”” <function run at 0x7f1ff5b95940>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    â”‚                 â”‚       â”” {'app': 'bot:app'}
    â”‚                 â”” ()
    â”” <function get_driver at 0x7f1ff5b954c0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    â”‚       â”” <function run at 0x7f1ff38b8670>
    â”” <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    â”‚      â”” <function Server.run at 0x7f1ff38b8a60>
    â”” <uvicorn.server.Server object at 0x7f1f87d52280>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           â”‚       â”‚   â”‚    â”‚             â”” None
           â”‚       â”‚   â”‚    â”” <function Server.serve at 0x7f1ff38b8af0>
           â”‚       â”‚   â”” <uvicorn.server.Server object at 0x7f1f87d52280>
           â”‚       â”” <function run at 0x7f1ff92ee430>
           â”” <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           â”‚    â”‚                  â”” <coroutine object Server.serve at 0x7f1f87caaf40>
           â”‚    â”” <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           â”” <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   â”‚   â”‚     â”‚   â”‚       â”‚   â”” <member 'kwargs' of 'Job' objects>
                   â”‚   â”‚     â”‚   â”‚       â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”‚     â”‚   â”” <member 'args' of 'Job' objects>
                   â”‚   â”‚     â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>
                   â”‚   â”” <member 'func' of 'Job' objects>
                   â”” <Job (id=43d481f940ca41fe9866a40cc14427da name=change_price)>

  File "./src/plugins/nonebot_plugin_russian/__init__.py", line 483, in change_price
    russian_manager._price_change_handle()
    â”‚               â”” <function RussianManager._price_change_handle at 0x7f1fe88494c0>
    â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 671, in _price_change_handle
    update_price = float(self._check_stock_handle()["money_per_stock"])+delta
                         â”‚    â”‚                                         â”” -1.807
                         â”‚    â”” <function RussianManager._check_stock_handle at 0x7f1fe8849430>
                         â”” <src.plugins.nonebot_plugin_russian.data_source.RussianManager object at 0x7f1fe8df1c70>

  File "./src/plugins/nonebot_plugin_russian/data_source.py", line 655, in _check_stock_handle
    money_per_stock =int(money_per_stock)
                         â”” '307.659'

ValueError: invalid literal for int() with base 10: '307.659'
[36mATRI[0m | 03-08 15:19:47 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    â”‚   â”‚    â”” <ClickAliasedGroup main>
    â”‚   â”” <built-in function exit>
    â”” <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           â”‚    â”‚     â”‚       â”” {}
           â”‚    â”‚     â”” ()
           â”‚    â”” <function BaseCommand.main at 0x7fd3fac86040>
           â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         â”‚    â”‚      â”” <click.core.Context object at 0x7fd3fb50c4f0>
         â”‚    â”” <function MultiCommand.invoke at 0x7fd3fac8a0d0>
         â”” <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           â”‚               â”‚       â”‚       â”‚      â”” <click.core.Context object at 0x7fd402df9370>
           â”‚               â”‚       â”‚       â”” <function Command.invoke at 0x7fd3fac86af0>
           â”‚               â”‚       â”” <ClickAliasedCommand run>
           â”‚               â”” <click.core.Context object at 0x7fd402df9370>
           â”” <function MultiCommand.invoke.<locals>._process_result at 0x7fd3f1bb29d0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           â”‚   â”‚      â”‚    â”‚           â”‚   â”” {'file': 'bot.py', 'app': 'app'}
           â”‚   â”‚      â”‚    â”‚           â”” <click.core.Context object at 0x7fd402df9370>
           â”‚   â”‚      â”‚    â”” <function run at 0x7fd3f1cdc8b0>
           â”‚   â”‚      â”” <ClickAliasedCommand run>
           â”‚   â”” <function Context.invoke at 0x7fd3fac828b0>
           â”” <click.core.Context object at 0x7fd402df9370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       â”‚       â”” {'file': 'bot.py', 'app': 'app'}
                       â”” ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    â”‚       â”‚     â”” 'app'
    â”‚       â”” 'bot.py'
    â”” <function run_bot at 0x7fd3f1ccb670>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             â”‚         â”‚             â”” 'bot'
             â”‚         â”” <function import_module at 0x7fd402e39940>
             â”” <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           â”‚          â”‚           â”‚    â”‚        â”‚        â”” 0
           â”‚          â”‚           â”‚    â”‚        â”” None
           â”‚          â”‚           â”‚    â”” 0
           â”‚          â”‚           â”” 'bot'
           â”‚          â”” <function _gcd_import at 0x7fd402f68430>
           â”” <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    â”‚       â”” <function load_plugins at 0x7fd3f8b4a790>
    â”” <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           â”‚       â”” <function PluginManager.load_all_plugins at 0x7fd3f8b44310>
           â”” <nonebot.plugin.manager.PluginManager object at 0x7fd3f14beac0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  â”‚    â”‚           â”‚         â”‚       â”‚    â”” <function PluginManager.list_plugins at 0x7fd3f8b441f0>
                  â”‚    â”‚           â”‚         â”‚       â”” <nonebot.plugin.manager.PluginManager object at 0x7fd3f14beac0>
                  â”‚    â”‚           â”‚         â”” 'nonebot_plugin_statistical'
                  â”‚    â”‚           â”” 'nonebot_plugin_statistical'
                  â”‚    â”” <function PluginManager.load_plugin at 0x7fd3f8b44280>
                  â”” <nonebot.plugin.manager.PluginManager object at 0x7fd3f14beac0>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             â”‚         â”” <function import_module at 0x7fd402e39940>
             â”” <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           â”‚          â”‚           â”‚    â”‚        â”‚        â”” 0
           â”‚          â”‚           â”‚    â”‚        â”” None
           â”‚          â”‚           â”‚    â”” 0
           â”‚          â”‚           â”” 'src.plugins.nonebot_plugin_statistical'
           â”‚          â”” <function _gcd_import at 0x7fd402f68430>
           â”” <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        â”” <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       â”‚    â”‚    â”” <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       â”‚    â”” <built-in function load>
                       â”” <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
