[36mATRI[0m | 03-03 21:08:29 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f9bfb403040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f9c03577130>
         │    └ <function MultiCommand.invoke at 0x7f9bfb4070d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f9c0357cca0>
           │               │       │       └ <function Command.invoke at 0x7f9bfb403af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f9c0357cca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f9bfbc50a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f9c0357cca0>
           │   │      │    └ <function run at 0x7f9bf244f5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f9bfb6808b0>
           └ <click.core.Context object at 0x7f9c0357cca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f9bf243f3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7f9c035b78b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7f9c036e6430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7f9bf927f3a0>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f9bf9270ee0>
           └ <nonebot.plugin.manager.PluginManager object at 0x7f9bf1c349d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7f9bf9270dc0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7f9bf1c349d0>
                  │    │           │         └ 'nonebot_plugin_statistical'
                  │    │           └ 'nonebot_plugin_statistical'
                  │    └ <function PluginManager.load_plugin at 0x7f9bf9270e50>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7f9bf1c349d0>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f9c035b78b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.nonebot_plugin_statistical'
           │          └ <function _gcd_import at 0x7f9c036e6430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       │    │    └ <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       │    └ <built-in function load>
                       └ <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-03 21:20:00 | ERROR apscheduler >> Job "memesfeiyu (trigger: cron[hour='21', minute='20'], next run at: 2022-03-04 21:20:00 CST)" raised an exception
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f9bfb403040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f9c03577130>
         │    └ <function MultiCommand.invoke at 0x7f9bfb4070d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f9c0357cca0>
           │               │       │       └ <function Command.invoke at 0x7f9bfb403af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f9c0357cca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f9bfbc50a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f9c0357cca0>
           │   │      │    └ <function run at 0x7f9bf244f5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f9bfb6808b0>
           └ <click.core.Context object at 0x7f9c0357cca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f9bf243f3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f9bf4548550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f9bf45480d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f9bf224b280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f9bf224b670>
    └ <uvicorn.server.Server object at 0x7f9bd510fb20>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f9bf224b700>
           │       │   └ <uvicorn.server.Server object at 0x7f9bd510fb20>
           │       └ <function run at 0x7f9bf7c960d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f9bd50bf840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/python3/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=12745 name=memesfeiyu)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=12745 name=memesfeiyu)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=12745 name=memesfeiyu)>

  File "./src/plugins/memes_from_feiyucans_space/__init__.py", line 25, in memesfeiyu
    msg = await suijitu()
                └ <function suijitu at 0x7f9bd51a8af0>

  File "./src/plugins/memes_from_feiyucans_space/__init__.py", line 75, in suijitu
    outtext = initext+'\n'+'[CQ:image,file='+pic+']'
              │                              └ {'img_height': 1152, 'img_size': 619.8447265625, 'img_src': 'https://i0.hdslb.com/bfs/album/23934fa0f1bb1cac596268a8aefd8937c...
              └ '{description} \n{posttime} \nfrom bilibili:鲱鱼罐头app'

TypeError: can only concatenate str (not "dict") to str
[36mATRI[0m | 03-03 21:39:24 | ERROR nonebot >> Running matcher <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f8fc88dc040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f8fd0a50130>
         │    └ <function MultiCommand.invoke at 0x7f8fc88e00d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f8fd0a55ca0>
           │               │       │       └ <function Command.invoke at 0x7f8fc88dcaf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f8fd0a55ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f8fc9129a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f8fd0a55ca0>
           │   │      │    └ <function run at 0x7f8fbf9285e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f8fc8b598b0>
           └ <click.core.Context object at 0x7f8fd0a55ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f8fbf9183a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f8fc1a21550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f8fc1a210d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f8fbf725280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f8fbf725670>
    └ <uvicorn.server.Server object at 0x7f8fa25d93a0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f8fbf725700>
           │       │   └ <uvicorn.server.Server object at 0x7f8fa25d93a0>
           │       └ <function run at 0x7f8fc516e0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f8fa262aa40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f8fc1a43d30>: <Task finished name='Task-3762' coro=<_command() done, defined at /usr/local/python3/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f8fa00bf040>
          │            │        │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1646314764, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f8fa195c400>
          │            └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7f8fbf842280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f8fc1a43d30>: <Task finished name='Task-3762' coro=<_command() done, defined at /usr/local/python3/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f8fa00bf040>
          │       │   │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │       │   │    └ GroupMessageEvent(time=1646314764, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f8fa195c400>
          │       └ <function Matcher.run at 0x7f8fc1a43790>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f8fc1a43d30>: <Task finished name='Task-3762' coro=<_command() done, defined at /usr/local/python3/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f8fa00bf040>
          │    │          │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │    │          │    └ GroupMessageEvent(time=1646314764, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f8fa195c400>
          │    └ <function Matcher.simple_run at 0x7f8fc1a43700>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function handle at 0x7f8fb4563c10>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f8fa195c400>, 'event': GroupMessageEvent(time=1646314764, self_id=5...
                 │    └ <function handle at 0x7f8fb4563c10>
                 └ <Dependent call=<function handle at 0x7f8fb4563c10>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...

  File "./src/plugins/trigger_memes_from_feiyucans_space.py", line 18, in handle
    response = requests.get(url=url, headers=headers)
                                │            └ {'User-Agent': 'Mozilla/5.0(Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/5...
                                └ 'https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?host_uid=45858772&offset_dynamic_id=0&need_top=1&platfo...

NameError: name 'requests' is not defined
[36mATRI[0m | 03-03 21:42:26 | ERROR nonebot >> Running matcher <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f6cdea60040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f6ce6bd4130>
         │    └ <function MultiCommand.invoke at 0x7f6cdea640d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f6ce6bd9ca0>
           │               │       │       └ <function Command.invoke at 0x7f6cdea60af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f6ce6bd9ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f6cdf2ada60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f6ce6bd9ca0>
           │   │      │    └ <function run at 0x7f6cd5aac5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f6cdecdd8b0>
           └ <click.core.Context object at 0x7f6ce6bd9ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f6cd5a9c3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f6cd7ba5550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f6cd7ba50d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f6cd58a9280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f6cd58a9670>
    └ <uvicorn.server.Server object at 0x7f6cb47817c0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f6cd58a9700>
           │       │   └ <uvicorn.server.Server object at 0x7f6cb47817c0>
           │       └ <function run at 0x7f6cdb2f20d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f6cb47ccb40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f6cd7bc7d30>: <Task finished name='Task-1052' coro=<_command() done, defined at /usr/local/python3/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6cb22c16d0>
          │            │        │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1646314946, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>
          │            └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7f6cd59c6280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f6cd7bc7d30>: <Task finished name='Task-1052' coro=<_command() done, defined at /usr/local/python3/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6cb22c16d0>
          │       │   │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │       │   │    └ GroupMessageEvent(time=1646314946, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>
          │       └ <function Matcher.run at 0x7f6cd7bc7790>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f6cd7bc7d30>: <Task finished name='Task-1052' coro=<_command() done, defined at /usr/local/python3/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6cb22c16d0>
          │    │          │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │    │          │    └ GroupMessageEvent(time=1646314946, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>
          │    └ <function Matcher.simple_run at 0x7f6cd7bc7700>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function handle at 0x7f6cb48cb670>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>, 'event': GroupMessageEvent(time=1646314946, self_id=5...
                 │    └ <function handle at 0x7f6cb48cb670>
                 └ <Dependent call=<function handle at 0x7f6cb48cb670>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...

  File "./src/plugins/trigger_memes_from_feiyucans_space.py", line 35, in handle
    card = json.loads(target['card'])
                      └ {'desc': {'uid': 45858772, 'type': 2, 'rid': 188122578, 'acl': 1024, 'view': 1086, 'repost': 0, 'comment': 1, 'like': 35, 'is...

NameError: name 'json' is not defined
[36mATRI[0m | 03-03 21:42:41 | ERROR nonebot >> Running matcher <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f6cdea60040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f6ce6bd4130>
         │    └ <function MultiCommand.invoke at 0x7f6cdea640d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f6ce6bd9ca0>
           │               │       │       └ <function Command.invoke at 0x7f6cdea60af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f6ce6bd9ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f6cdf2ada60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f6ce6bd9ca0>
           │   │      │    └ <function run at 0x7f6cd5aac5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f6cdecdd8b0>
           └ <click.core.Context object at 0x7f6ce6bd9ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f6cd5a9c3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f6cd7ba5550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f6cd7ba50d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f6cd58a9280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f6cd58a9670>
    └ <uvicorn.server.Server object at 0x7f6cb47817c0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f6cd58a9700>
           │       │   └ <uvicorn.server.Server object at 0x7f6cb47817c0>
           │       └ <function run at 0x7f6cdb2f20d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f6cb47ccb40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f6cd7bc7d30>: <Task finished name='Task-1886' coro=<_command() done, defined at /usr/local/python3/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6cb04a3250>
          │            │        │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1646314960, self_id=507346814, post_type='message', sub_type='normal', user_id=1020936395, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>
          │            └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7f6cd59c6280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f6cd7bc7d30>: <Task finished name='Task-1886' coro=<_command() done, defined at /usr/local/python3/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6cb04a3250>
          │       │   │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │       │   │    └ GroupMessageEvent(time=1646314960, self_id=507346814, post_type='message', sub_type='normal', user_id=1020936395, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>
          │       └ <function Matcher.run at 0x7f6cd7bc7790>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f6cd7bc7d30>: <Task finished name='Task-1886' coro=<_command() done, defined at /usr/local/python3/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6cb04a3250>
          │    │          │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │    │          │    └ GroupMessageEvent(time=1646314960, self_id=507346814, post_type='message', sub_type='normal', user_id=1020936395, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>
          │    └ <function Matcher.simple_run at 0x7f6cd7bc7700>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function handle at 0x7f6cb48cb670>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>, 'event': GroupMessageEvent(time=1646314960, self_id=5...
                 │    └ <function handle at 0x7f6cb48cb670>
                 └ <Dependent call=<function handle at 0x7f6cb48cb670>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...

  File "./src/plugins/trigger_memes_from_feiyucans_space.py", line 35, in handle
    card = json.loads(target['card'])
                      └ {'desc': {'uid': 45858772, 'type': 2, 'rid': 188122578, 'acl': 1024, 'view': 1086, 'repost': 0, 'comment': 1, 'like': 35, 'is...

NameError: name 'json' is not defined
[36mATRI[0m | 03-03 21:43:54 | ERROR nonebot >> Running matcher <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f6cdea60040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f6ce6bd4130>
         │    └ <function MultiCommand.invoke at 0x7f6cdea640d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f6ce6bd9ca0>
           │               │       │       └ <function Command.invoke at 0x7f6cdea60af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f6ce6bd9ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f6cdf2ada60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f6ce6bd9ca0>
           │   │      │    └ <function run at 0x7f6cd5aac5e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f6cdecdd8b0>
           └ <click.core.Context object at 0x7f6ce6bd9ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f6cd5a9c3a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f6cd7ba5550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f6cd7ba50d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f6cd58a9280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f6cd58a9670>
    └ <uvicorn.server.Server object at 0x7f6cb47817c0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f6cd58a9700>
           │       │   └ <uvicorn.server.Server object at 0x7f6cb47817c0>
           │       └ <function run at 0x7f6cdb2f20d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f6cb47ccb40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f6cd7bc7d30>: <Task finished name='Task-13682' coro=<_command() done, defined at /usr/local/python3...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6cb049f190>
          │            │        │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1646315034, self_id=507346814, post_type='message', sub_type='normal', user_id=1020936395, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>
          │            └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7f6cd59c6280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f6cd7bc7d30>: <Task finished name='Task-13682' coro=<_command() done, defined at /usr/local/python3...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6cb049f190>
          │       │   │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │       │   │    └ GroupMessageEvent(time=1646315034, self_id=507346814, post_type='message', sub_type='normal', user_id=1020936395, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>
          │       └ <function Matcher.run at 0x7f6cd7bc7790>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f6cd7bc7d30>: <Task finished name='Task-13682' coro=<_command() done, defined at /usr/local/python3...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6cb049f190>
          │    │          │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │    │          │    └ GroupMessageEvent(time=1646315034, self_id=507346814, post_type='message', sub_type='normal', user_id=1020936395, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>
          │    └ <function Matcher.simple_run at 0x7f6cd7bc7700>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function handle at 0x7f6cb48cb670>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6cb3b3ff10>, 'event': GroupMessageEvent(time=1646315034, self_id=5...
                 │    └ <function handle at 0x7f6cb48cb670>
                 └ <Dependent call=<function handle at 0x7f6cb48cb670>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...

  File "./src/plugins/trigger_memes_from_feiyucans_space.py", line 35, in handle
    card = json.loads(target['card'])
                      └ {'desc': {'uid': 45858772, 'type': 2, 'rid': 188122578, 'acl': 1024, 'view': 1088, 'repost': 0, 'comment': 1, 'like': 35, 'is...

NameError: name 'json' is not defined
[36mATRI[0m | 03-03 21:44:12 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fb9acc06040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fb9b4d7a130>
         │    └ <function MultiCommand.invoke at 0x7fb9acc0a0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fb9b4d7fca0>
           │               │       │       └ <function Command.invoke at 0x7fb9acc06af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fb9b4d7fca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fb9ad453a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fb9b4d7fca0>
           │   │      │    └ <function run at 0x7fb9a3c525e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fb9ace838b0>
           └ <click.core.Context object at 0x7fb9b4d7fca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fb9a3c423a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7fb9b4dba8b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7fb9b4ee9430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7fb9aaa823a0>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7fb9aaa74ee0>
           └ <nonebot.plugin.manager.PluginManager object at 0x7fb9a34379a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7fb9aaa74dc0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7fb9a34379a0>
                  │    │           │         └ 'nonebot_plugin_statistical'
                  │    │           └ 'nonebot_plugin_statistical'
                  │    └ <function PluginManager.load_plugin at 0x7fb9aaa74e50>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7fb9a34379a0>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7fb9b4dba8b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.nonebot_plugin_statistical'
           │          └ <function _gcd_import at 0x7fb9b4ee9430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       │    │    └ <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       │    └ <built-in function load>
                       └ <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-03 21:44:42 | ERROR nonebot >> Running matcher <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fb9acc06040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fb9b4d7a130>
         │    └ <function MultiCommand.invoke at 0x7fb9acc0a0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fb9b4d7fca0>
           │               │       │       └ <function Command.invoke at 0x7fb9acc06af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fb9b4d7fca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fb9ad453a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fb9b4d7fca0>
           │   │      │    └ <function run at 0x7fb9a3c525e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fb9ace838b0>
           └ <click.core.Context object at 0x7fb9b4d7fca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fb9a3c423a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fb9a5d4b550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fb9a5d4b0d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fb9a3a4f280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fb9a3a4f670>
    └ <uvicorn.server.Server object at 0x7fb98299f790>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fb9a3a4f700>
           │       │   └ <uvicorn.server.Server object at 0x7fb98299f790>
           │       └ <function run at 0x7fb9a94990d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fb982916f40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _event_to_me at 0x7fb9a5d6dc10>: <Task finished name='Task-4211' coro=<_event_to_me() done, defined at /usr/local/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fb98044d4f0>
          │            │        │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1646315082, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb981c94070>
          │            └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7fb9a3b6c280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _event_to_me at 0x7fb9a5d6dc10>: <Task finished name='Task-4211' coro=<_event_to_me() done, defined at /usr/local/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fb98044d4f0>
          │       │   │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │       │   │    └ GroupMessageEvent(time=1646315082, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb981c94070>
          │       └ <function Matcher.run at 0x7fb9a5d6d790>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _event_to_me at 0x7fb9a5d6dc10>: <Task finished name='Task-4211' coro=<_event_to_me() done, defined at /usr/local/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fb98044d4f0>
          │    │          │    │      └ {'_prefix': {'command': ('昨日最佳',), 'raw_command': '/昨日最佳', 'command_arg': []}}
          │    │          │    └ GroupMessageEvent(time=1646315082, self_id=507346814, post_type='message', sub_type='normal', user_id=2560359315, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb981c94070>
          │    └ <function Matcher.simple_run at 0x7fb9a5d6d700>
          └ <Matcher from src.plugins.trigger_memes_from_feiyucans_space, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function handle at 0x7fb99b5d0f70>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb981c94070>, 'event': GroupMessageEvent(time=1646315082, self_id=5...
                 │    └ <function handle at 0x7fb99b5d0f70>
                 └ <Dependent call=<function handle at 0x7fb99b5d0f70>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name...

  File "./src/plugins/trigger_memes_from_feiyucans_space.py", line 46, in handle
    outtext = initext+'\n'+'[CQ:image,file='+pic+']'
              │                              └ {'img_height': 1152, 'img_size': 619.8447265625, 'img_src': 'https://i0.hdslb.com/bfs/album/23934fa0f1bb1cac596268a8aefd8937c...
              └ '{description} \n{posttime} \nfrom bilibili:鲱鱼罐头app'

TypeError: can only concatenate str (not "dict") to str
[36mATRI[0m | 03-03 21:47:28 | ERROR plugin.manager >> Failed to import "nonebot_plugin_statistical"
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fc98da78040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fc995bec130>
         │    └ <function MultiCommand.invoke at 0x7fc98da7c0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fc995bf1ca0>
           │               │       │       └ <function Command.invoke at 0x7fc98da78af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fc995bf1ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fc98e2c5a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fc995bf1ca0>
           │   │      │    └ <function run at 0x7fc984ac45e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fc98dcf48b0>
           └ <click.core.Context object at 0x7fc995bf1ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fc984ab43a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
             │         │             └ 'bot'
             │         └ <function import_module at 0x7fc995c2c8b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'bot'
           │          └ <function _gcd_import at 0x7fc995d5b430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./bot.py", line 29, in <module>
    nonebot.load_plugins("src/plugins")
    │       └ <function load_plugins at 0x7fc98b8f43a0>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7fc98b8e6ee0>
           └ <nonebot.plugin.manager.PluginManager object at 0x7fc9842a9910>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7fc98b8e6dc0>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7fc9842a9910>
                  │    │           │         └ 'nonebot_plugin_statistical'
                  │    │           └ 'nonebot_plugin_statistical'
                  │    └ <function PluginManager.load_plugin at 0x7fc98b8e6e50>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7fc9842a9910>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7fc995c2c8b0>
             └ <module 'importlib' from '/usr/local/python3/lib/python3.8/importlib/__init__.py'>
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'src.plugins.nonebot_plugin_statistical'
           │          └ <function _gcd_import at 0x7fc995d5b430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'src.plugins.nonebot_plugin_statistical' from './src/plugins/nonebot_plugin_statistical/__init__.py'>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "./src/plugins/nonebot_plugin_statistical/__init__.py", line 1, in <module>
    from .statistical_hook import *

  File "./src/plugins/nonebot_plugin_statistical/statistical_hook.py", line 7, in <module>
    from .config import save_data, get_prefix_group_count_dict, get_prefix_user_count_dict, \

  File "./src/plugins/nonebot_plugin_statistical/config.py", line 149, in <module>
    plugin2cmd: dict = json.load(f)
                       │    │    └ <_io.TextIOWrapper name='/root/Projects/Kori-Bot/Kori-bot/data/statistical/plugin2cmd.json' mode='r' encoding='utf8'>
                       │    └ <built-in function load>
                       └ <module 'ujson' from '/usr/local/python3/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so'>

ValueError: Expected object or value
[36mATRI[0m | 03-03 22:48:15 | ERROR nonebot >> Running matcher <Matcher from src.plugins.nonebot_plugin_songpicker2, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f6c4939b040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f6c5150f130>
         │    └ <function MultiCommand.invoke at 0x7f6c4939f0d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f6c51514ca0>
           │               │       │       └ <function Command.invoke at 0x7f6c4939baf0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7f6c51514ca0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f6c49be8a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7f6c51514ca0>
           │   │      │    └ <function run at 0x7f6c403e75e0>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7f6c496178b0>
           └ <click.core.Context object at 0x7f6c51514ca0>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7f6c403d73a0>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7f6c424e0550>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7f6c424e00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f6c401e4280>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f6c401e4670>
    └ <uvicorn.server.Server object at 0x7f6c1f079ac0>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f6c401e4700>
           │       │   └ <uvicorn.server.Server object at 0x7f6c1f079ac0>
           │       └ <function run at 0x7f6c45c2d0d0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f6c1f0e5d40>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f6c42502d30>: <Task finished name='Task-121800' coro=<_command() done, defined at /usr/local/python...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6c175b8370>
          │            │        │    │      └ {'_prefix': {'command': ('点歌',), 'raw_command': '/点歌', 'command_arg': [MessageSegment(type='text', data={'text': 'freedom'})]}}
          │            │        │    └ GroupMessageEvent(time=1646318895, self_id=507346814, post_type='message', sub_type='normal', user_id=1020936395, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6c1e425ac0>
          │            └ <Matcher from src.plugins.nonebot_plugin_songpicker2, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7f6c40301280>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f6c42502d30>: <Task finished name='Task-121800' coro=<_command() done, defined at /usr/local/python...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6c175b8370>
          │       │   │    │      └ {'_prefix': {'command': ('点歌',), 'raw_command': '/点歌', 'command_arg': [MessageSegment(type='text', data={'text': 'freedom'})]}}
          │       │   │    └ GroupMessageEvent(time=1646318895, self_id=507346814, post_type='message', sub_type='normal', user_id=1020936395, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6c1e425ac0>
          │       └ <function Matcher.run at 0x7f6c42502790>
          └ <Matcher from src.plugins.nonebot_plugin_songpicker2, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f6c42502d30>: <Task finished name='Task-121800' coro=<_command() done, defined at /usr/local/python...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f6c175b8370>
          │    │          │    │      └ {'_prefix': {'command': ('点歌',), 'raw_command': '/点歌', 'command_arg': [MessageSegment(type='text', data={'text': 'freedom'})]}}
          │    │          │    └ GroupMessageEvent(time=1646318895, self_id=507346814, post_type='message', sub_type='normal', user_id=1020936395, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6c1e425ac0>
          │    └ <function Matcher.simple_run at 0x7f6c42502700>
          └ <Matcher from src.plugins.nonebot_plugin_songpicker2, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function handle_songName at 0x7f6c37168940>, params=[ModelField(name='bot', type=Bot, required=True), ModelF...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f6c1e425ac0>, 'event': GroupMessageEvent(time=1646318895, self_id=5...
                 │    └ <function handle_songName at 0x7f6c37168940>
                 └ <Dependent call=<function handle_songName at 0x7f6c37168940>, params=[ModelField(name='bot', type=Bot, required=True), ModelF...

  File "./src/plugins/nonebot_plugin_songpicker2/__init__.py", line 39, in handle_songName
    songName = state["songName"]

NameError: name 'state' is not defined
